---
title: "Ideología en Guatemala"
author: "Javier Brolo"
date: 2017-10-13T21:13:14-05:00
categories: []
tags: []
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

La siguiente gráfica interactiva muestra el porcentaje de guatemaltecos que respondieron con cada opción a cada pregunta realizada por el Barómetro de las Américas de 2017. Es posible filtrar los grupos de guatemaltecos según características demográficas como: género, población urbana o rural, etnicidad o grupo etáreo. 

A diferencia del discurso público, el cuál está mediado por relaciones de poder y sesgos de selección, que hacen ciertos discursos más visibles que otros, las encuestas representativas de la población dan la misma atención a todos los ciudadanos por igual. Por ello, encuestas como las elaboradas por LAPOP sirven de complemento al análisis que busca entender qué opinan los guatemaltecos sobre diversos temas. Ahora bien, aunque las encuestas permiten observar que tan común o inusual es una opinión en la población, por si mismas, estas no ofrecen información sobre los argumentos, experiencias e interpretaciones que llevan a una persona a sostener dichas opiniones. 

Espero que el ejercicio de explorar las información y descubrir que opinan los guatemaltecos sea de interés al lector. Si desean dejar un comentario compartiendo algo que les llamara la atención, otros podremos aprender de ver la información desde esa perspectiva.   



<iframe width = "100%" height = "1050px" seamless frameborder = "0" src="https://javierbrolo.shinyapps.io/barplotsurvey/"></iframe>



### Referencias:

I thank the Latin American Public Opinion Project (LAPOP) and its major supporters (the United States Agency for International Development, the Inter-American Development Bank, and Vanderbilt University) for making the data available.

The AmericasBarometer by the Latin American Public Opinion Project (LAPOP), http://www.LapopSurveys.org.
